### ISSUE TITLE
Support for other versions?

### ISSUE THREAD

**Issue by jack980517** [MikuAuahDark/SIF_Win32#1]
SIF has 5 versions in total: CN, TW, EN, JP, KR. Is the other 4 versions supported now? If not, would the support be added later?

**Comment by MikuAuahDark** [comment]
All of it are supported already in v2.1 (if I remember) and above
26 Jul 2016 02.45, "Jacqueline" <notifications@github.com> menulis:

**Comment by MikuAuahDark** [comment]
RIP I just notice it. Other version support can be added easily but not for
JP. It will require many changes in the code and I don't have time for it
because school.
27 Jul 2016 05.26, "Cameron" <notifications@github.com> menulis:

**Comment by MikuAuahDark** [comment]
Some info:

* SIF KR is no longer exists, but KR game data is backward compatible with JP game data.

* Starting from v0.3 (15433b4f3148eaa83dc3e06cc36b9d045c2c7ee8), the whole decryption code now relies to libhonoka for decrypting game files which means that all of versions you said above is now supported.
